"""HTTP API versioning constants (Phase 13.1)."""

from __future__ import annotations

SERVING_API_MAJOR_VERSION = "v1"
SERVING_API_ROUTE_PREFIX = f"/api/{SERVING_API_MAJOR_VERSION}"

PLANNED_ROUTE_HEALTH = f"{SERVING_API_ROUTE_PREFIX}/health"
PLANNED_ROUTE_READY = f"{SERVING_API_ROUTE_PREFIX}/ready"
PLANNED_ROUTE_SEARCH = f"{SERVING_API_ROUTE_PREFIX}/search"
PLANNED_ROUTE_RECOMMENDATIONS = f"{SERVING_API_ROUTE_PREFIX}/recommendations"
PLANNED_ROUTE_PRODUCT = f"{SERVING_API_ROUTE_PREFIX}/products/{{product_id}}"

__all__ = [
    "PLANNED_ROUTE_HEALTH",
    "PLANNED_ROUTE_PRODUCT",
    "PLANNED_ROUTE_READY",
    "PLANNED_ROUTE_RECOMMENDATIONS",
    "PLANNED_ROUTE_SEARCH",
    "SERVING_API_MAJOR_VERSION",
    "SERVING_API_ROUTE_PREFIX",
]
