"""Application exception types."""

from productiq.exceptions.base import (
    CatalogLoadError,
    CatalogValidationError,
    ConfigurationError,
    DataAttributeError,
    DatabaseError,
    DataCatalogError,
    DataCleaningError,
    DataDeduplicationError,
    DataExportError,
    DataIngestionError,
    DataNormalizationError,
    DataValidationError,
    FilteringRepresentationError,
    LexicalRetrievalError,
    PgvectorExtensionError,
    ProductIQError,
    ProductRepresentationError,
    QueryRepresentationError,
    RankingError,
    RecommendationError,
    RepresentationDatasetError,
    RepresentationQualityError,
    RetrievalError,
    SemanticRetrievalError,
    ValidationError,
)

__all__ = [
    "CatalogLoadError",
    "CatalogValidationError",
    "ConfigurationError",
    "DataAttributeError",
    "DataCatalogError",
    "DataCleaningError",
    "DataDeduplicationError",
    "DataExportError",
    "DataIngestionError",
    "DataNormalizationError",
    "DataValidationError",
    "DatabaseError",
    "FilteringRepresentationError",
    "LexicalRetrievalError",
    "PgvectorExtensionError",
    "ProductIQError",
    "ProductRepresentationError",
    "QueryRepresentationError",
    "RankingError",
    "RecommendationError",
    "RepresentationDatasetError",
    "RepresentationQualityError",
    "RetrievalError",
    "SemanticRetrievalError",
    "ValidationError",
]
