"""Constants for Phase 4.11 product embedding artifacts."""

from __future__ import annotations

from productiq.representation.dataset_schema import (
    CHECKSUM_ALGORITHM,
    REPRESENTATION_DATASET_NAME,
    REPRESENTATION_MANIFEST_FILENAME,
    REPRESENTATION_PARQUET_FILENAME,
    SEMANTIC_TEXT_COLUMN,
)

PRODUCT_EMBEDDINGS_DATASET_NAME = "product_embeddings"
PRODUCT_EMBEDDINGS_FILENAME = "product_embeddings.parquet"
PRODUCT_EMBEDDINGS_MANIFEST_FILENAME = "product_embeddings.manifest.json"
PRODUCT_EMBEDDINGS_SCHEMA_VERSION = "1.0.0"
PRODUCT_EMBEDDINGS_FORMAT = "parquet"
PRODUCT_EMBEDDINGS_PIPELINE_PHASE = "4.11"

EMBEDDING_INPUT_PRODUCT_ID_COLUMN = "product_id"
EMBEDDING_INPUT_SEMANTIC_TEXT_COLUMN = SEMANTIC_TEXT_COLUMN
EMBEDDING_OUTPUT_COLUMN = "embedding"

BGE_PRIMARY_MODEL_ID = "BAAI/bge-small-en-v1.5"
BGE_QUERY_INSTRUCTION = "Represent this sentence for searching relevant passages: "
SIMILARITY_METRIC_COSINE = "cosine"
NORMALIZATION_L2 = "l2"
DOCUMENT_ENCODING_RULE = "raw semantic_text without instruction prefix"

DEFAULT_EMBEDDING_BATCH_SIZE = 64
DEFAULT_EMBEDDING_CUDA_BATCH_SIZE = 32
DEFAULT_EMBEDDING_READ_BATCH_SIZE = 10_000
UNIT_NORM_TOLERANCE = 1e-3
EXPECTED_CATALOG_PRODUCT_COUNT = 367_172
PRODUCTIQ_EMBEDDING_DIMENSION = 384

__all__ = [
    "BGE_PRIMARY_MODEL_ID",
    "BGE_QUERY_INSTRUCTION",
    "CHECKSUM_ALGORITHM",
    "DEFAULT_EMBEDDING_BATCH_SIZE",
    "DEFAULT_EMBEDDING_CUDA_BATCH_SIZE",
    "DEFAULT_EMBEDDING_READ_BATCH_SIZE",
    "DOCUMENT_ENCODING_RULE",
    "EMBEDDING_INPUT_PRODUCT_ID_COLUMN",
    "EMBEDDING_INPUT_SEMANTIC_TEXT_COLUMN",
    "EMBEDDING_OUTPUT_COLUMN",
    "EXPECTED_CATALOG_PRODUCT_COUNT",
    "NORMALIZATION_L2",
    "PRODUCTIQ_EMBEDDING_DIMENSION",
    "PRODUCT_EMBEDDINGS_DATASET_NAME",
    "PRODUCT_EMBEDDINGS_FILENAME",
    "PRODUCT_EMBEDDINGS_FORMAT",
    "PRODUCT_EMBEDDINGS_MANIFEST_FILENAME",
    "PRODUCT_EMBEDDINGS_PIPELINE_PHASE",
    "PRODUCT_EMBEDDINGS_SCHEMA_VERSION",
    "REPRESENTATION_DATASET_NAME",
    "REPRESENTATION_MANIFEST_FILENAME",
    "REPRESENTATION_PARQUET_FILENAME",
    "SIMILARITY_METRIC_COSINE",
    "UNIT_NORM_TOLERANCE",
]
