"""Schema constants for Phase 4.6 BM25 lexical index artifacts."""

from __future__ import annotations

from data.export.schema import CHECKSUM_ALGORITHM
from productiq.representation.dataset_schema import (
    LEXICAL_TEXT_COLUMN,
    REPRESENTATION_DATASET_NAME,
    REPRESENTATION_DATASET_SCHEMA_VERSION,
    REPRESENTATION_MANIFEST_FILENAME,
    REPRESENTATION_PARQUET_FILENAME,
)

BM25_LEXICAL_INDEX_SCHEMA_VERSION = "1.0.0"
BM25_LEXICAL_INDEX_NAME = "bm25_lexical_index"
BM25_LEXICAL_INDEX_FORMAT = "pickle"
BM25_LEXICAL_INDEX_FILENAME = "bm25_lexical_index.pkl"
BM25_LEXICAL_INDEX_MANIFEST_FILENAME = "bm25_lexical_index.manifest.json"
BM25_LEXICAL_INDEX_PIPELINE_PHASE = "4.6"
LEXICAL_TOKENIZER_IDENTIFIER = "productiq.retrieval.lexical.tokenize_lexical_text/v1"

INDEX_INPUT_PRODUCT_ID_COLUMN = "product_id"
INDEX_INPUT_LEXICAL_TEXT_COLUMN = LEXICAL_TEXT_COLUMN

DEFAULT_INDEX_BUILD_BATCH_SIZE = 10_000

__all__ = [
    "BM25_LEXICAL_INDEX_FILENAME",
    "BM25_LEXICAL_INDEX_FORMAT",
    "BM25_LEXICAL_INDEX_MANIFEST_FILENAME",
    "BM25_LEXICAL_INDEX_NAME",
    "BM25_LEXICAL_INDEX_PIPELINE_PHASE",
    "BM25_LEXICAL_INDEX_SCHEMA_VERSION",
    "CHECKSUM_ALGORITHM",
    "DEFAULT_INDEX_BUILD_BATCH_SIZE",
    "INDEX_INPUT_LEXICAL_TEXT_COLUMN",
    "INDEX_INPUT_PRODUCT_ID_COLUMN",
    "LEXICAL_TOKENIZER_IDENTIFIER",
    "REPRESENTATION_DATASET_NAME",
    "REPRESENTATION_DATASET_SCHEMA_VERSION",
    "REPRESENTATION_MANIFEST_FILENAME",
    "REPRESENTATION_PARQUET_FILENAME",
]
