"""Schema constants for Phase 4.12 PostgreSQL/pgvector product vector index."""

from __future__ import annotations

from productiq.retrieval.embedding_schema import (
    BGE_PRIMARY_MODEL_ID,
    CHECKSUM_ALGORITHM,
    EXPECTED_CATALOG_PRODUCT_COUNT,
    PRODUCT_EMBEDDINGS_FILENAME,
    PRODUCT_EMBEDDINGS_MANIFEST_FILENAME,
    PRODUCT_EMBEDDINGS_SCHEMA_VERSION,
    PRODUCTIQ_EMBEDDING_DIMENSION,
    SIMILARITY_METRIC_COSINE,
)

PRODUCT_VECTOR_INDEX_SCHEMA_VERSION = "1.0.0"
PRODUCT_VECTOR_INDEX_NAME = "product_vector_index"
PRODUCT_VECTOR_INDEX_PIPELINE_PHASE = "4.12"
PRODUCT_VECTOR_INDEX_MANIFEST_FILENAME = "product_vector_index.manifest.json"

PGVECTOR_DISTANCE_METRIC = "cosine"
PGVECTOR_OPERATOR_CLASS = "vector_cosine_ops"
PGVECTOR_INDEX_TYPE = "hnsw"

# Initial HNSW parameters (not tuned for production SLA).
HNSW_M = 16
HNSW_EF_CONSTRUCTION = 64

DEFAULT_VECTOR_INDEX_LOAD_BATCH_SIZE = 5_000

OFFICIAL_EMBEDDING_ARTIFACT_CHECKSUM = (
    "d97a843f54ca2cc404bcce7955fb86edc066c9f504f66e82fc1d9d6a23316dc6"
)
OFFICIAL_SOURCE_REPRESENTATION_CHECKSUM = (
    "7fc2b6c08ef03233bdae1c845f4a087cd578fdb6d861b7d64ec72c71e92c3379"
)

__all__ = [
    "BGE_PRIMARY_MODEL_ID",
    "CHECKSUM_ALGORITHM",
    "DEFAULT_VECTOR_INDEX_LOAD_BATCH_SIZE",
    "EXPECTED_CATALOG_PRODUCT_COUNT",
    "HNSW_EF_CONSTRUCTION",
    "HNSW_M",
    "OFFICIAL_EMBEDDING_ARTIFACT_CHECKSUM",
    "OFFICIAL_SOURCE_REPRESENTATION_CHECKSUM",
    "PGVECTOR_DISTANCE_METRIC",
    "PGVECTOR_INDEX_TYPE",
    "PGVECTOR_OPERATOR_CLASS",
    "PRODUCTIQ_EMBEDDING_DIMENSION",
    "PRODUCT_EMBEDDINGS_FILENAME",
    "PRODUCT_EMBEDDINGS_MANIFEST_FILENAME",
    "PRODUCT_EMBEDDINGS_SCHEMA_VERSION",
    "PRODUCT_VECTOR_INDEX_MANIFEST_FILENAME",
    "PRODUCT_VECTOR_INDEX_NAME",
    "PRODUCT_VECTOR_INDEX_PIPELINE_PHASE",
    "PRODUCT_VECTOR_INDEX_SCHEMA_VERSION",
    "SIMILARITY_METRIC_COSINE",
]
